//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorizes
    {
        public categorizes()
        {
            this.ExportedCategories = new HashSet<ExportedCategory>();
            this.MovedCategories = new HashSet<MovedCategory>();
            this.StoredCategories = new HashSet<StoredCategory>();
            this.ImportedCategories = new HashSet<ImportedCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UnitM { get; set; }
        public int Amount { get; set; }
    
        public virtual ICollection<ExportedCategory> ExportedCategories { get; set; }
        public virtual ICollection<MovedCategory> MovedCategories { get; set; }
        public virtual ICollection<StoredCategory> StoredCategories { get; set; }
        public virtual ICollection<ImportedCategory> ImportedCategories { get; set; }
    }
}
