//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Exports = new HashSet<Export>();
        }
    
        public int Id { get; set; }
        public string CName { get; set; }
        public int CPhone { get; set; }
        public string Fax { get; set; }
        public int Tele { get; set; }
        public string Mail { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<Export> Exports { get; set; }
    }
}
