//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public Export()
        {
            this.ExportedCategories = new HashSet<ExportedCategory>();
        }
    
        public int Id { get; set; }
        public string StoreName { get; set; }
        public System.DateTime Date { get; set; }
        public int ClientsId { get; set; }
    
        public virtual ICollection<ExportedCategory> ExportedCategories { get; set; }
        public virtual Clients Client { get; set; }
    }
}
