//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public Import()
        {
            this.ImportedCategories = new HashSet<ImportedCategory>();
        }
    
        public int Id { get; set; }
        public string StoreName { get; set; }
        public System.DateTime Date { get; set; }
        public int SuppliersId { get; set; }
    
        public virtual ICollection<ImportedCategory> ImportedCategories { get; set; }
        public virtual Suppliers Supplier { get; set; }
    }
}
