//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovedCategory
    {
        public int MovmentsId { get; set; }
        public int categorizesId { get; set; }
    
        public virtual categorizes categorize { get; set; }
        public virtual Movments Movment { get; set; }
    }
}
