//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movments
    {
        public Movments()
        {
            this.MovedCategories = new HashSet<MovedCategory>();
        }
    
        public int Id { get; set; }
        public string FromStore { get; set; }
        public string ToStore { get; set; }
        public int Amount { get; set; }
    
        public virtual ICollection<MovedCategory> MovedCategories { get; set; }
    }
}
