//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectContainer : DbContext
    {
        public ProjectContainer()
            : base("name=ProjectContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categorizes> categorizes1 { get; set; }
        public DbSet<Import> Imports1 { get; set; }
        public DbSet<Export> Exports { get; set; }
        public DbSet<ImportedCategory> ImportedCategories { get; set; }
        public DbSet<ExportedCategory> ExportedCategories { get; set; }
        public DbSet<Movments> Movments { get; set; }
        public DbSet<MovedCategory> MovedCategories { get; set; }
        public DbSet<StoredCategory> StoredCategories { get; set; }
        public DbSet<stores> stores { get; set; }
        public DbSet<Suppliers> Suppliers1 { get; set; }
        public DbSet<Clients> Clients { get; set; }
    }
}
