//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class stores
    {
        public stores()
        {
            this.StoredCategories = new HashSet<StoredCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string ManagerName { get; set; }
    
        public virtual ICollection<StoredCategory> StoredCategories { get; set; }
    }
}
